[package]
name = "seal-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "seal"
path = "src/main.rs"

[dependencies]
seal-engine = { path = "../seal-engine" }
age.workspace = true
clap.workspace = true
rpassword.workspace = true

[dev-dependencies]
tempfile = "3"
seal-engine = { path = "../seal-engine" }

[lints]
workspace = true
