[package]
name = "seal-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
libc = "0.2"
xattr = "1"

[dev-dependencies]
tempfile = "3"
xattr = "1"
libc = "0.2"

[lints]
workspace = true
